### ISSUE TITLE
Error when updating a user with no plateID

### ISSUE THREAD

**Issue by mahdibenromdhane** [Charge-Angels/ev-dashboard#2000]

**Comment by OliveGerste** [comment]
I do not get an error when I update a user without a plateID. So seems to be solved.
Two things I noticed:
- plateID is not removable anymore, once it is set (Is this on purpose? Maybe the user does not own a car anymore at some point)
- plateID ist Admin only, so a user has to contact an admin to change it or the user does not know, that the field exists and it is not changed, if e.g. a new car is owned.

**Comment by LucasBrazi06** [comment]
> I do not get an error when I update a user without a plateID. So seems to be solved.
> Two things I noticed:
> 
> * plateID is not removable anymore, once it is set (Is this on purpose? Maybe the user does not own a car anymore at some point)
> * plateID ist Admin only, so a user has to contact an admin to change it or the user does not know, that the field exists and it is not changed, if e.g. a new car is owned.

Good remarks!
At the beginning only the admin can enter this information but now that we have car management, the user can create his own car with the plate ID.
We kept it for users not finding their car in car management so we can make it available for Basic users also.
We should also allow empty value in this field.
@mahdibenromdhane Could you create an issue and take care of these two small devs?
Thanks both!

**Comment by mahdibenromdhane** [comment]
> > I do not get an error when I update a user without a plateID. So seems to be solved.
> > Two things I noticed:
> > 
> > * plateID is not removable anymore, once it is set (Is this on purpose? Maybe the user does not own a car anymore at some point)
> > * plateID ist Admin only, so a user has to contact an admin to change it or the user does not know, that the field exists and it is not changed, if e.g. a new car is owned.
> 
> Good remarks!
> At the beginning only the admin can enter this information but now that we have car management, the user can create his own car with the plate ID.
> We kept it for users not finding their car in car management so we can make it available for Basic users also.
> We should also allow empty value in this field.
> @mahdibenromdhane Could you create an issue and take care of these two small devs?
> Thanks both!

OK :)

**Comment by WillyLellouch** [comment]
This issue seems to be resolved and tested. Could I have a confirmation ?

**Comment by LucasBrazi06** [comment]
> This issue seems to be resolved and tested. Could I have a confirmation ?

Check with the developper.

**Comment by WillyLellouch** [comment]
@mahdibenromdhane, @OliveGerste, any news on that ?

**Comment by mahdibenromdhane** [comment]
> @mahdibenromdhane, @OliveGerste, any news on that ?

It's resolved, no error when updating a user with no plateID

**Comment by WillyLellouch** [comment]
> It's resolved, no error when updating a user with no plateID


I'll just close the issue then.
